name: Update Index

on:
  push:
    branches: [ main ]
    paths:
      - '**.tgz'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Helm Installation
        uses: azure/setup-helm@v3.5
        with:
          version: v3.12.3
      - name: Update Index
        run: |
          helm repo index .
          git config --global user.email "yourbot@yourorg.com"
          git config --global user.name "YourOrg Bot"
          git add index.yaml
          git commit -m "Update chart index"
          git push
